theme: jekyll-theme-minimal

logo: /assets/tanvir.jpg

author:
  name: Tanvir
  email: <tanvirnwu@g.skku.edu>

github_username: tanvirnwu

header_pages: 
  - pages/publications.md

github: 
  is_project_page: false
  
