theme: jekyll-theme-minimal

# title: "&nbsp;"
title: " "
# description: [A short description of your site's purpose]
# show_downloads: [false]
github:
  zip_url: https://fb.com/
  another_url: https://fb.com/
  
logo: /assets/tanvir8.png

author:
  name: Tanvir
  email: <tanvirnwu@g.skku.edu>

# github_username: " "

header_pages:
  - pages/publications.md
  - pages/datasets.md

github: 
  is_project_page: false
  
