theme: jekyll-theme-minimal

logo: /assets/tanvir.jpg

author:
  name: Tanvir
  email: <tanvirnwu@g.skku.edu>

github_username: tanvirnwu

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages: 
  - about.md


description: > # your text below (remove <br> elements if you don't need line breaks)
  
 <div style="text-align: center;">
  <a href="https://example.com" style="text-decoration: none;" target="_blank">
    <button style="padding: 10px 20px; font-size: 16px; color: black; background-color: white; border: none; border-radius: 5px; cursor: pointer; margin: 5px; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);">
      Portfolio
    </button>
  </a>
  <a href="https://example.com" style="text-decoration: none;" target="_blank">
    <button style="padding: 10px 20px; font-size: 16px; color: black; background-color: white; border: none; border-radius: 5px; cursor: pointer; margin: 5px; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);">
      Download CV
    </button>
  </a>
  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  
  <style>
    button:hover {
      background-color: #1a75ff !important; /* Blue background on hover */
      color: #ffffff !important; /* White text on hover */
    }
  </style>






