theme: jekyll-theme-minimal

logo: /assets/tanvir.jpg


navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
