theme: jekyll-theme-minimal

logo: /assets/tanvir.jpg


description: > # your text below (remove <br> elements if you don't need line breaks)
  A US Army veteran and analyst with data science, statistics, machine learning, programming, and management background. 
  Over six years of data analysis and twenty years of team and program managment. Experienced communicator having briefed internal and external 
  stakeholders on analysis findings and courses of action. 
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-lundeen-b49b8390/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br><br>
  <a href="https://rpubs.com/jacoblundeen"> <img src="https://img.shields.io/badge/RPubs-blue?logo=R"> </a>
