theme: jekyll-theme-minimal

# title: "&nbsp;"
title: " "
# description: [A short description of your site's purpose]

logo: /assets/tanvir5.png

author:
  name: Tanvir
  email: <tanvirnwu@g.skku.edu>

github_username: tanvirnwu

header_pages: 
  - pages/publications.md

github: 
  is_project_page: false
  
