theme: jekyll-theme-minimal

logo: /assets/tanvir.jpg

author:
  name: Tanvir
  email: <tanvirnwu@g.skku.edu>

github_username: tanvirnwu

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages: 
  - about.md
  - publications.md

github: # For removing the "View My GitHub Profile" Link 
  is_project_page: false
  
description: > # your text below (remove <br> elements if you don't need line breaks)
  <div style="text-align: center; position: relative; display: inline-block;">
    <button onclick="toggleDropdown()" style="padding: 10px 40px; font-size: 16px; color: white; background-color: #0066ff; border: none; border-radius: 5px; cursor: pointer; margin: 5px; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); font-weight: bold;">
      Menu
    </button>
    <div id="myDropdown" style="display: none; position: absolute; background-color: white; box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.1); border-radius: 5px; z-index: 1; min-width: 160px;">
      <a href="https://example.com" target="_blank" style="color: black; padding: 12px 16px; text-decoration: none; display: block; border-bottom: 1px solid #f1f1f1;">Portfolio</a>
      <a href="https://example.com" target="_blank" style="color: black; padding: 12px 16px; text-decoration: none; display: block; border-bottom: 1px solid #f1f1f1;">Download CV</a>
      <a href="/publications" target="_blank" style="color: black; padding: 12px 16px; text-decoration: none; display: block;">Publications</a>
    </div>
  </div>
  <br>
  <div style="text-align: center;">
    <a href="/publications" style="text-decoration: none;">
      <button style="padding: 10px 40px; font-size: 16px; color: white; background-color: #0066ff; border: none; border-radius: 5px; cursor: pointer; margin: 5px; box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); font-weight: bold;">
        View Publications
      </button>
    </a>
  </div>

  <style>
    button:hover {
      background-color: white !important; /* White background on hover */
      color: #0066ff !important; /* Blue text on hover */
    }

    a:hover {
      background-color: #ddd;
      color: black;
    }

    .dropdown-content a {
      padding: 12px 16px;
      text-decoration: none;
      display: block;
      color: black;
    }

    .dropdown-content a:hover {
      background-color: #f1f1f1;
    }
  </style>

  <script>
    function toggleDropdown() {
      var dropdown = document.getElementById("myDropdown");
      if (dropdown.style.display === "none") {
        dropdown.style.display = "block";
      } else {
        dropdown.style.display = "none";
      }
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function(event) {
      if (!event.target.matches('button')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        for (var i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.style.display === "block") {
            openDropdown.style.display = "none";
          }
        }
      }
    }
  </script>
